on:
  push:
    paths:
        - 'dataset/**'
        - 'scripts/**'
        - 'source/**'
  pull_request:
    paths:
      - 'dataset/**'
      - 'scripts/**'
      - 'source/**'

name: Build 

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        
    steps:
      - uses: actions/checkout@v3
      - name: Build trimal for Linux x86_64
        if: matrix.arch == 'x86_64'
        run: cd source && make all && file trimal && file readal && file statal &&
          cd .. && ./scripts/generate_trimmed_msas.sh && ./scripts/compare_trimmed_msas.sh

      - name: Build trimal for Linux aarch64
        if: matrix.arch == 'aarch64'
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/trimal" 
          install: |
            apt-get update -q -y
            apt-get install -q -y make g++ file
          run: |
            cd /trimal/source && make all && file trimal && file readal && file statal &&
            cd .. && ./scripts/generate_trimmed_msas.sh && ./scripts/compare_trimmed_msas.sh
